### ISSUE TITLE
Setting duration to "dog" (or any other unparseable value) responds with a 500 error

### ISSUE THREAD

**Issue by ahungry** [mre/zerocal#10]
Setting duration to "dog" (or any other unparseable value) responds with a 500 error.

I was just noticing this when reading the blog article and thinking about how rust doesn't necessarily protect from logic edge cases :smile:

**Comment by mre** [comment]
You found an easter egg. 😆

**Comment by mre** [comment]
This is fixed in master now. Thanks for reporting.
