### ISSUE TITLE
Add support for QR code generation

### ISSUE THREAD

**Issue by sebasrp** [mre/zerocal#13]
Use case: as a meeting organizer, i want to quickly create an event on my phone, then share that meeting with my friends though a QR code on my phone

QR code would either be the link to the event or the link to the calendar file

**Comment by mre** [comment]
Sounds like fun. Basically we could do it as described here: https://dev.to/murtuzaalisurti/how-to-make-a-qr-code-generator-using-vanilla-javascript-3cla

I would point to the calendar file directly. On iOS it automatically opens the calendar then I hope. (On Android it just downloads the .ics file)
