### ISSUE TITLE
A clone in Typescript/Deno Deploy

### ISSUE THREAD

**Issue by maheshsundaram** [mre/zerocal#15]
Hi! I really liked this project and found it inspiring to make a clone in Typescript on Deno Deploy. If you are curious you can see it here - https://kiwical.deno.dev/ Thank you for the inspiration!

**Comment by mre** [comment]
Hey Mahesh, this looks amazing! Feel free to create a pull request to add your project to the zerocal `README.md`. 👍

**Comment by maheshsundaram** [comment]
Hey Matthias, thank you for offering, that's very kind. I create this PR #16 I'm not sure "derivatives" is the right word, but that was the best I could think of!
