### ISSUE TITLE
Add example bash command to create a calendar event from the command line

### ISSUE THREAD

**Issue by mre** [mre/zerocal#6]
Example:

```bash
curl https://zerocal.shuttleapp.rs?start=2022-11-04+20:00&duration=3h&title=Birthday&description=paaarty
```

**Comment by ahungry** [comment]
```sh
curl -LG  zerocal.shuttleapp.rs -d start=2022-11-04+20:00 -d duration=3h -d title=Birthday -d description=paaarty
```
might be slightly more readable (at least for terminals that don't highlight the `&` like github has in your comment) - you could make a small bash one liner that prompts for each value as well.

**Comment by mre** [comment]
Learning something new about curl every day. Very nice indeed. Let's go with that!

**Comment by mre** [comment]
Changed the format to what you suggested. Thanks!
